"""instagram_post: patrones por tipo

Revision ID: 27216c7e1b48
Revises: e540fa99d80a
Create Date: 2026-08-24 06:43:54.635657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27216c7e1b48'
down_revision: Union[str, None] = 'e540fa99d80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('publicado_en', sa.DateTime(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_post')
    # ### end Alembic commands ###
