"""user: stripe subscription redes

Revision ID: 57cc868c449e
Revises: ebee69d71cf8
Create Date: 2026-08-25 00:48:20.324603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cc868c449e'
down_revision: Union[str, None] = 'ebee69d71cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column(
        'user', sa.Column('suscripcion_redes_activa', sa.Boolean(), server_default='false', nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'suscripcion_redes_activa')
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
