"""advice: veredictos de fase 2

Revision ID: 584e7d162fd2
Revises: 369dfa3b646e
Create Date: 2026-08-19 03:52:58.374320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '584e7d162fd2'
down_revision: Union[str, None] = '369dfa3b646e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('veredicto', sa.Enum('RESURTE', 'NO_PIDAS', 'VIGILA', name='veredicto'), nullable=False),
    sa.Column('confianza', sa.Enum('ALTA', 'BAJA', name='confianza'), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('datos_que_lo_respaldan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice')
    # ### end Alembic commands ###
