"""instagram_daily_metric y racha

Revision ID: 8bd6805015a9
Revises: 719a71507e26
Create Date: 2026-08-24 05:12:14.788992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd6805015a9'
down_revision: Union[str, None] = '719a71507e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_daily_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('accounts_engaged', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('publico_contenido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'fecha')
    )
    op.add_column('instagram_account', sa.Column('racha_actual', sa.Integer(), server_default='0', nullable=False))
    op.add_column('instagram_account', sa.Column('racha_maxima', sa.Integer(), server_default='0', nullable=False))
    op.add_column('instagram_account', sa.Column('ultima_fecha_publicacion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_account', 'ultima_fecha_publicacion')
    op.drop_column('instagram_account', 'racha_maxima')
    op.drop_column('instagram_account', 'racha_actual')
    op.drop_table('instagram_daily_metric')
    # ### end Alembic commands ###
