"""user: email_verificado

Revision ID: a3dfb899d0db
Revises: 27216c7e1b48
Create Date: 2026-08-24 07:18:44.445094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dfb899d0db'
down_revision: Union[str, None] = '27216c7e1b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verificado', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verificado')
    # ### end Alembic commands ###
