"""ondelete cascade en todas las FK de business/user

Revision ID: ebee69d71cf8
Revises: a3dfb899d0db
Create Date: 2026-08-24 07:48:56.398293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebee69d71cf8'
down_revision: Union[str, None] = 'a3dfb899d0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('advice_product_id_fkey'), 'advice', type_='foreignkey')
    op.drop_constraint(op.f('advice_business_id_fkey'), 'advice', type_='foreignkey')
    op.create_foreign_key(None, 'advice', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'advice', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('business_user_id_fkey'), 'business', type_='foreignkey')
    op.create_foreign_key(None, 'business', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('business_context_business_id_fkey'), 'business_context', type_='foreignkey')
    op.create_foreign_key(None, 'business_context', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_message_business_id_fkey'), 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('content_tip_business_id_fkey'), 'content_tip', type_='foreignkey')
    op.create_foreign_key(None, 'content_tip', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('daily_question_business_id_fkey'), 'daily_question', type_='foreignkey')
    op.create_foreign_key(None, 'daily_question', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('instagram_account_business_id_fkey'), 'instagram_account', type_='foreignkey')
    op.create_foreign_key(None, 'instagram_account', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('instagram_daily_metric_business_id_fkey'), 'instagram_daily_metric', type_='foreignkey')
    op.create_foreign_key(None, 'instagram_daily_metric', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('instagram_post_business_id_fkey'), 'instagram_post', type_='foreignkey')
    op.create_foreign_key(None, 'instagram_post', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_business_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sale_business_id_fkey'), 'sale', type_='foreignkey')
    op.drop_constraint(op.f('sale_variant_id_fkey'), 'sale', type_='foreignkey')
    op.create_foreign_key(None, 'sale', 'variant', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sale', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('stock_variant_id_fkey'), 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'variant', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('variant_product_id_fkey'), 'variant', type_='foreignkey')
    op.create_foreign_key(None, 'variant', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variant', type_='foreignkey')
    op.create_foreign_key(op.f('variant_product_id_fkey'), 'variant', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key(op.f('stock_variant_id_fkey'), 'stock', 'variant', ['variant_id'], ['id'])
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.create_foreign_key(op.f('sale_variant_id_fkey'), 'sale', 'variant', ['variant_id'], ['id'])
    op.create_foreign_key(op.f('sale_business_id_fkey'), 'sale', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_business_id_fkey'), 'product', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'instagram_post', type_='foreignkey')
    op.create_foreign_key(op.f('instagram_post_business_id_fkey'), 'instagram_post', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'instagram_daily_metric', type_='foreignkey')
    op.create_foreign_key(op.f('instagram_daily_metric_business_id_fkey'), 'instagram_daily_metric', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'instagram_account', type_='foreignkey')
    op.create_foreign_key(op.f('instagram_account_business_id_fkey'), 'instagram_account', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'daily_question', type_='foreignkey')
    op.create_foreign_key(op.f('daily_question_business_id_fkey'), 'daily_question', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'content_tip', type_='foreignkey')
    op.create_foreign_key(op.f('content_tip_business_id_fkey'), 'content_tip', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key(op.f('chat_message_business_id_fkey'), 'chat_message', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'business_context', type_='foreignkey')
    op.create_foreign_key(op.f('business_context_business_id_fkey'), 'business_context', 'business', ['business_id'], ['id'])
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.create_foreign_key(op.f('business_user_id_fkey'), 'business', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'advice', type_='foreignkey')
    op.drop_constraint(None, 'advice', type_='foreignkey')
    op.create_foreign_key(op.f('advice_business_id_fkey'), 'advice', 'business', ['business_id'], ['id'])
    op.create_foreign_key(op.f('advice_product_id_fkey'), 'advice', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
